Default: &defaults
  host: "*4"
  port: 3000
  copyright: (c) 2012
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost/"
  <<: *defaults
