Default: &defaults
  database: ecksy.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ecksy_test.sqlite3
  <<: *defaults

Staging:
  database: ecksy_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ecksy_production.sqlite3
  poolsize: 100
  <<: *defaults
